import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Partners from "./components/Partners";
import Courses from "./courses/page";
import Acheivement from "./achivement/page";
import Coursesname from "./coursesname/page";
import Team from "./team/page"
import Testimonials from "./testimonials/page";
import Footer from "./components/Footer"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  overflow-x-hidden`}
      
      >
        <Header />
        {children}
        <Partners />
        <Courses />
        <Acheivement />
        <Coursesname />
        <Team />
        <Testimonials />
        <Footer />

      </body>
    </html>
  );
}
